### ISSUE TITLE
Support introspection of individual fields, listing value ranges, and list of values and counts of their occurrence for discrete value fields (string, integer)

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#10]
Similar concerns as for search and collection introspection.

**Comment by coreyo** [comment]
right now the "stored" field returned by the getField() method invariably returns "false".  I am still trying to figure out how to determine whether a field is stored.

**Comment by datadavev** [comment]
Take a look at: http://wiki.apache.org/solr/LukeRequestHandler

Will need to modify getFields() of the solrclient to parse the flags.
