### ISSUE TITLE
Ensure appropriate test coverage is available for gateway API methods.

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#12]
Setup unit test frame work to exercise the gateway APIs. This can be a standalone python module that verifies the structure of responses from the gateway is as expected. 

Additional checks such as character encoding and escaping can be added to this framework as needed.

**Comment by coreyo** [comment]
Dave created some initial test modules in src/gw_test

**Comment by coreyo** [comment]
All subsequent code has been standardized to work with Python 2.5.x, since that is the latest python officially supported by the Google Appengine servers.  I think that the initial unit tests might use libraries packaged only in later versions of python.  We might want to change this.

**Comment by datadavev** [comment]
Meant to close this one instead of #16 - tests updated to use features available in python2.5.

Additional tests should be added as functionality changes, but closing this for now as api testing is complete enough.
