### ISSUE TITLE
Gateway API - URL Encoding / Decoding

### ISSUE THREAD

**Issue by coreyo** [datadavev/DwC_views#17]
Many URL "GET" values located in the requests that are passed to the Gateway API should be URL encoded/escaped to maintain their integrity.  LIkewise, each of these parameters should be URL decoded by the API when a request is received.

**Comment by coreyo** [comment]
Is there any reason to handle this specifically?  Question: Does Django automatically URLDecode GET variables?

**Comment by datadavev** [comment]
It appears that Django will handle this just fine. There may be some consideration within the client, particularly for encoding the query string for getRecords requests.

**Comment by coreyo** [comment]
I am being careful to do this (for instance, when you input a search or an ID in a textbox).   Do we want to keep this as a rolling ticket, or would you like to close it?

**Comment by datadavev** [comment]
Closing this as it appear to be a non-issue.
