### ISSUE TITLE
Ensure the Djano gateway application operates in standalone mode.

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#2]
The appengine app should also be able to run independently of appengine as a standard Django application. This task is to ensure that is the case and to ensure there is a mechanism to deploy as a standard django app as well as an appengine app.

**Comment by coreyo** [comment]
The initial commit of the dwc_app_view works as both an appengine application and a standalone django application.  This can be tested using the standard "manage.py runserver" script from within the dwc_app_view directory.  This will be an ongoing task, as we must regularly check that all functionality works under both environments.
