### ISSUE TITLE
retrieve content from some web source and pass through django gateway app

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#3]
Implement a Django view that provides efficient passthrough of content to a
web browser client. The view should accept as a parameter a URL and return
the content to the client by retrieving from the target of the URL using the
HTTP GET method and streaming the response to the client. The major
considerations here are performance and scalability - the results of the
HTTP GET operation MUST be streamed to the client, not retrieved then
forwarded to the client in separate steps.

**Comment by coreyo** [comment]
I'm not sure exactly what you want on this one, but you said that we've exceeded this, so I'm going to close it.
