### ISSUE TITLE
DwC JQuery Client - Map View: Initial Center & Zoom

### ISSUE THREAD

**Issue by coreyo** [datadavev/DwC_views#36]
When the map is initialized (or receiving a new filter or record set), the map should center itself between the markers and zoom appropriately.

**Comment by datadavev** [comment]
The map view should maintain state, so that when a user flips between the records view and map view, the map view should retain the previous extents unless a new filter has been specified by the user changing the result set to be displayed.

**Comment by coreyo** [comment]
The initial implementation of this was easy, however, coordinating this with regular "idle" event dynamic marker loading proved challenging.
