### ISSUE TITLE
DwC JQuery Client - Map View: Dynamic Markers (onZoom/onScroll)

### ISSUE THREAD

**Issue by coreyo** [datadavev/DwC_views#37]
In the case of too many markers, we can load additional markers dynamically as the client zooms in and/or scrolls around the map.

**Comment by datadavev** [comment]
The bounding box filter expression would be something like:

```
lng:[\-85.2 TO \-52.8] AND lat:[23.4 TO 42.6]
```

Adding to an existing filter (user entered) might look something like:

```
sciName_s:"Citharichthys cornutus" AND lng:[\-85.2 TO \-52.8] AND lat:[23.4 TO 42.6]
```

For bounds that cross the 180th meridian, it will be necessary to use a sub expression for the longitudinal constraint. e.g. for longitude ranging from 170.2 to -125.1 across the 180th meridian:

```
sciName_s:"Citharichthys cornutus" AND (lng:[170.2 TO 180.0] OR lng:[\-180.0 TO \-125.1]) AND lat:[23.4 TO 42.6]
```

**Comment by coreyo** [comment]
This is accomplished by attaching an internal map view function to the 'idle' event in the actual google maps api
