### ISSUE TITLE
Escape terms in SOLR filters

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#39]
When programmatically generating filters being sent to SOLR, it is necessary to ensure that any values in the filter expression are properly escaped.

Filter expressions entered by the user should be assumed to be properly escaped.

A script that does this in python (from solrclient.py):

``` python

  def escapeQueryTerm(self, term):
    '''
    + - && || ! ( ) { } [ ] ^ " ~ * ? : \
    '''
    reserved = ['+','-','&','|','!','(',')','{','}','[',']','^','"','~','*','?',':',]
    term = term.replace(u'\\',u'\\\\')
    for c in reserved:
      term = term.replace(c,u"\%s" % c)
    return term
```

**Comment by coreyo** [comment]
solrEscapeValue() has been created, takes a string and returns the string with the solrEscapeCharacter inserted in front of each special character, as listed in solrSpecialCharacters.  Various functions are now using this function.
