### ISSUE TITLE
Commit code and notes to GitHub

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#4]
All code and notes need to be committed to the project repository for the milestone to be considered complete.

Actual rate of commit should be on a functional basis - when a feature is complete, commit the code. In some cases (e.g. large tasks) it may be necessary to commit more frequently which is OK provided the commit log indicates such.

**Comment by coreyo** [comment]
We will use Sphinx for standard Python Documentation.  I will close this ticket when all python code has been tagged with the proper Sphinx tags.

**Comment by coreyo** [comment]
All code has been submitted to GitHub.  Sphinx documentation pending...
