### ISSUE TITLE
resultset not preserved between views

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#42]
After setting a filter in the filter bar, the expected behavior is for the records view and the map view to show the same records.

The user filter appears to be missing from the map view, which seems to always show everything. Switching to the records view shows the expected resultset.

**Comment by coreyo** [comment]
The filter and the dynamic marker loading were not playing nicely together.  The issue was already known, and has since been resolved in the working code.  Problem will be fixed in the next commit.
