### ISSUE TITLE
DwC JQuery Client - Field View

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#49]
This is a new plugin that will show the characteristics of a single field within the Darwin Core Database.

The field view should show the field type, the total number of distinct terms, the minimum value, maximum value, and a rendering of the distinct terms based on their value and frequency of occurrence (e.g. word cloud or histogram).

The values should reflect the current active filter.

**Comment by coreyo** [comment]
The Min/Max values present a slight problem.  They are not shown in the original field view.  We can potentially grab them from the /values or /histogram gateway function, however if we decide to implement a "top X" parameter in the values (which I think might be a good idea for word clouds with too many values), this might also pose a problem.  Haven't given the solution much thought yet.  What do you suggest?

**Comment by datadavev** [comment]
Hi Corey,
I found a "stats" module that provides useful information for continuous
value fields. For example:

http://serrano.speciesanalyst.net/solr/select?indent=on&rows=0&stats=true&stats.field=mintemp_f&q=species_s:hexapterus

I'm undecided on whether the min and max values have any real meaning for
string fields.

**Comment by datadavev** [comment]
The field view should show values for the currently active filter. So record count, word cloud, histogram and other values should be modified by the current filter.
