### ISSUE TITLE
Report on activities for milestone

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#5]
Report on activities, and recommendations or concerns that need to be
addressed for the ongoing project activities.

**Comment by coreyo** [comment]
The proposed memcache service is from the google appengine API and therefore will not work with a standalone django setup.  Do we want to look into using a different, more portable service?

**Comment by datadavev** [comment]
Yep. Django has fairly decent caching functionality - take a look and evaluate if that might provide a viable alternative to memcache.  https://docs.djangoproject.com/en/dev/topics/cache/

**Comment by coreyo** [comment]
I have moved the memcache discussion over to its dedicated ticket: issue #14 .  I am now closing this ticket.  Further discussion will take place in subsequent milestones.
