### ISSUE TITLE
Fleshout gateway API docs.

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#6]
Need to complete the gateway api docs prior to implementation.

**Comment by coreyo** [comment]
Dave wrote the initial Gateway API docs, though he is adding more to the design.  I will be adding sphinx documentation to the code implemention shortly.  Is there anything else that is required for this ticket?

**Comment by datadavev** [comment]
Pretty much complete. There may be some additional changes to API, but only as a result of discussion between Corey and Dave.
