### ISSUE TITLE
implement search operation on gateway

### ISSUE THREAD

**Issue by datadavev** [datadavev/DwC_views#8]
Implement search on gateway.

Client invokes search on gateway, gateway executes search against SOLR index, returning results to client.

Pass through must be efficient, streaming if possible. It will likely be necessary to transform results as they pass through the gateway, so consideration for this implementation should be taken into account.

**Comment by coreyo** [comment]
Dave, can you clarify the purpose of this ticket.  Does this refer only to the getRecords() method in the gateway API, or does this include the actual frontend search UI interface which calls the getRecords() function?
